/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as ApiAdminRolesRouteImport } from './routes/api/admin/roles'
import { Route as ApiAdminSeedDemoRouteImport } from './routes/api/admin/seed-demo'
import { Route as ApiAdminStaffInvitesRouteImport } from './routes/api/admin/staff-invites'
import { Route as ApiAnnouncementsIndexRouteImport } from './routes/api/announcements/index'
import { Route as ApiAttendanceFeedRouteImport } from './routes/api/attendance/feed'
import { Route as ApiAttendanceHistoryRouteImport } from './routes/api/attendance/history'
import { Route as ApiAuthDemoLoginRouteImport } from './routes/api/auth/demo-login'
import { Route as ApiAuthLoginDirectRouteImport } from './routes/api/auth/login-direct'
import { Route as ApiAuthRegisterOrgRouteImport } from './routes/api/auth/register-org'
import { Route as ApiCheckInScanRouteImport } from './routes/api/check-in/scan'
import { Route as ApiKioskPairRouteImport } from './routes/api/kiosk/pair'
import { Route as ApiKioskPairCodeRouteImport } from './routes/api/kiosk/pair-code'
import { Route as ApiKioskTokenRouteImport } from './routes/api/kiosk/token'
import { Route as ApiLocationsIndexRouteImport } from './routes/api/locations/index'
import { Route as ApiLocationsRevokeRouteImport } from './routes/api/locations/revoke'
import { Route as ApiOrganizationIndexRouteImport } from './routes/api/organization/index'
import { Route as ApiPushNotificationsRouteImport } from './routes/api/push/notifications'
import { Route as ApiPushPreferencesRouteImport } from './routes/api/push/preferences'
import { Route as ApiPushSendRouteImport } from './routes/api/push/send'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiPushVapidKeyRouteImport } from './routes/api/push/vapid-key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRolesRoute = ApiAdminRolesRouteImport.update({
  id: '/api/admin/roles',
  path: '/api/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSeedDemoRoute = ApiAdminSeedDemoRouteImport.update({
  id: '/api/admin/seed-demo',
  path: '/api/admin/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStaffInvitesRoute = ApiAdminStaffInvitesRouteImport.update({
  id: '/api/admin/staff-invites',
  path: '/api/admin/staff-invites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementsIndexRoute = ApiAnnouncementsIndexRouteImport.update({
  id: '/api/announcements/',
  path: '/api/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceFeedRoute = ApiAttendanceFeedRouteImport.update({
  id: '/api/attendance/feed',
  path: '/api/attendance/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceHistoryRoute = ApiAttendanceHistoryRouteImport.update({
  id: '/api/attendance/history',
  path: '/api/attendance/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDemoLoginRoute = ApiAuthDemoLoginRouteImport.update({
  id: '/api/auth/demo-login',
  path: '/api/auth/demo-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginDirectRoute = ApiAuthLoginDirectRouteImport.update({
  id: '/api/auth/login-direct',
  path: '/api/auth/login-direct',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterOrgRoute = ApiAuthRegisterOrgRouteImport.update({
  id: '/api/auth/register-org',
  path: '/api/auth/register-org',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckInScanRoute = ApiCheckInScanRouteImport.update({
  id: '/api/check-in/scan',
  path: '/api/check-in/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKioskPairRoute = ApiKioskPairRouteImport.update({
  id: '/api/kiosk/pair',
  path: '/api/kiosk/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKioskPairCodeRoute = ApiKioskPairCodeRouteImport.update({
  id: '/api/kiosk/pair-code',
  path: '/api/kiosk/pair-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKioskTokenRoute = ApiKioskTokenRouteImport.update({
  id: '/api/kiosk/token',
  path: '/api/kiosk/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationsIndexRoute = ApiLocationsIndexRouteImport.update({
  id: '/api/locations/',
  path: '/api/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationsRevokeRoute = ApiLocationsRevokeRouteImport.update({
  id: '/api/locations/revoke',
  path: '/api/locations/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationIndexRoute = ApiOrganizationIndexRouteImport.update({
  id: '/api/organization/',
  path: '/api/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushNotificationsRoute = ApiPushNotificationsRouteImport.update({
  id: '/api/push/notifications',
  path: '/api/push/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushPreferencesRoute = ApiPushPreferencesRouteImport.update({
  id: '/api/push/preferences',
  path: '/api/push/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSendRoute = ApiPushSendRouteImport.update({
  id: '/api/push/send',
  path: '/api/push/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushVapidKeyRoute = ApiPushVapidKeyRouteImport.update({
  id: '/api/push/vapid-key',
  path: '/api/push/vapid-key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/api/admin/roles': typeof ApiAdminRolesRoute
  '/api/admin/seed-demo': typeof ApiAdminSeedDemoRoute
  '/api/admin/staff-invites': typeof ApiAdminStaffInvitesRoute
  '/api/attendance/feed': typeof ApiAttendanceFeedRoute
  '/api/attendance/history': typeof ApiAttendanceHistoryRoute
  '/api/auth/demo-login': typeof ApiAuthDemoLoginRoute
  '/api/auth/login-direct': typeof ApiAuthLoginDirectRoute
  '/api/auth/register-org': typeof ApiAuthRegisterOrgRoute
  '/api/check-in/scan': typeof ApiCheckInScanRoute
  '/api/kiosk/pair': typeof ApiKioskPairRoute
  '/api/kiosk/pair-code': typeof ApiKioskPairCodeRoute
  '/api/kiosk/token': typeof ApiKioskTokenRoute
  '/api/locations/revoke': typeof ApiLocationsRevokeRoute
  '/api/push/notifications': typeof ApiPushNotificationsRoute
  '/api/push/preferences': typeof ApiPushPreferencesRoute
  '/api/push/send': typeof ApiPushSendRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/vapid-key': typeof ApiPushVapidKeyRoute
  '/api/announcements/': typeof ApiAnnouncementsIndexRoute
  '/api/locations/': typeof ApiLocationsIndexRoute
  '/api/organization/': typeof ApiOrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/api/admin/roles': typeof ApiAdminRolesRoute
  '/api/admin/seed-demo': typeof ApiAdminSeedDemoRoute
  '/api/admin/staff-invites': typeof ApiAdminStaffInvitesRoute
  '/api/attendance/feed': typeof ApiAttendanceFeedRoute
  '/api/attendance/history': typeof ApiAttendanceHistoryRoute
  '/api/auth/demo-login': typeof ApiAuthDemoLoginRoute
  '/api/auth/login-direct': typeof ApiAuthLoginDirectRoute
  '/api/auth/register-org': typeof ApiAuthRegisterOrgRoute
  '/api/check-in/scan': typeof ApiCheckInScanRoute
  '/api/kiosk/pair': typeof ApiKioskPairRoute
  '/api/kiosk/pair-code': typeof ApiKioskPairCodeRoute
  '/api/kiosk/token': typeof ApiKioskTokenRoute
  '/api/locations/revoke': typeof ApiLocationsRevokeRoute
  '/api/push/notifications': typeof ApiPushNotificationsRoute
  '/api/push/preferences': typeof ApiPushPreferencesRoute
  '/api/push/send': typeof ApiPushSendRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/vapid-key': typeof ApiPushVapidKeyRoute
  '/api/announcements': typeof ApiAnnouncementsIndexRoute
  '/api/locations': typeof ApiLocationsIndexRoute
  '/api/organization': typeof ApiOrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/api/admin/roles': typeof ApiAdminRolesRoute
  '/api/admin/seed-demo': typeof ApiAdminSeedDemoRoute
  '/api/admin/staff-invites': typeof ApiAdminStaffInvitesRoute
  '/api/attendance/feed': typeof ApiAttendanceFeedRoute
  '/api/attendance/history': typeof ApiAttendanceHistoryRoute
  '/api/auth/demo-login': typeof ApiAuthDemoLoginRoute
  '/api/auth/login-direct': typeof ApiAuthLoginDirectRoute
  '/api/auth/register-org': typeof ApiAuthRegisterOrgRoute
  '/api/check-in/scan': typeof ApiCheckInScanRoute
  '/api/kiosk/pair': typeof ApiKioskPairRoute
  '/api/kiosk/pair-code': typeof ApiKioskPairCodeRoute
  '/api/kiosk/token': typeof ApiKioskTokenRoute
  '/api/locations/revoke': typeof ApiLocationsRevokeRoute
  '/api/push/notifications': typeof ApiPushNotificationsRoute
  '/api/push/preferences': typeof ApiPushPreferencesRoute
  '/api/push/send': typeof ApiPushSendRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/vapid-key': typeof ApiPushVapidKeyRoute
  '/api/announcements/': typeof ApiAnnouncementsIndexRoute
  '/api/locations/': typeof ApiLocationsIndexRoute
  '/api/organization/': typeof ApiOrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kiosk'
    | '/privacy'
    | '/scan'
    | '/terms'
    | '/account'
    | '/announcements'
    | '/dashboard'
    | '/departments'
    | '/history'
    | '/reports'
    | '/settings'
    | '/accept-invite/$token'
    | '/api/admin/roles'
    | '/api/admin/seed-demo'
    | '/api/admin/staff-invites'
    | '/api/attendance/feed'
    | '/api/attendance/history'
    | '/api/auth/demo-login'
    | '/api/auth/login-direct'
    | '/api/auth/register-org'
    | '/api/check-in/scan'
    | '/api/kiosk/pair'
    | '/api/kiosk/pair-code'
    | '/api/kiosk/token'
    | '/api/locations/revoke'
    | '/api/push/notifications'
    | '/api/push/preferences'
    | '/api/push/send'
    | '/api/push/subscribe'
    | '/api/push/vapid-key'
    | '/api/announcements/'
    | '/api/locations/'
    | '/api/organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kiosk'
    | '/privacy'
    | '/scan'
    | '/terms'
    | '/account'
    | '/announcements'
    | '/dashboard'
    | '/departments'
    | '/history'
    | '/reports'
    | '/settings'
    | '/accept-invite/$token'
    | '/api/admin/roles'
    | '/api/admin/seed-demo'
    | '/api/admin/staff-invites'
    | '/api/attendance/feed'
    | '/api/attendance/history'
    | '/api/auth/demo-login'
    | '/api/auth/login-direct'
    | '/api/auth/register-org'
    | '/api/check-in/scan'
    | '/api/kiosk/pair'
    | '/api/kiosk/pair-code'
    | '/api/kiosk/token'
    | '/api/locations/revoke'
    | '/api/push/notifications'
    | '/api/push/preferences'
    | '/api/push/send'
    | '/api/push/subscribe'
    | '/api/push/vapid-key'
    | '/api/announcements'
    | '/api/locations'
    | '/api/organization'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kiosk'
    | '/privacy'
    | '/scan'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/announcements'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/history'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/accept-invite/$token'
    | '/api/admin/roles'
    | '/api/admin/seed-demo'
    | '/api/admin/staff-invites'
    | '/api/attendance/feed'
    | '/api/attendance/history'
    | '/api/auth/demo-login'
    | '/api/auth/login-direct'
    | '/api/auth/register-org'
    | '/api/check-in/scan'
    | '/api/kiosk/pair'
    | '/api/kiosk/pair-code'
    | '/api/kiosk/token'
    | '/api/locations/revoke'
    | '/api/push/notifications'
    | '/api/push/preferences'
    | '/api/push/send'
    | '/api/push/subscribe'
    | '/api/push/vapid-key'
    | '/api/announcements/'
    | '/api/locations/'
    | '/api/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KioskRoute: typeof KioskRoute
  PrivacyRoute: typeof PrivacyRoute
  ScanRoute: typeof ScanRoute
  TermsRoute: typeof TermsRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  ApiAdminRolesRoute: typeof ApiAdminRolesRoute
  ApiAdminSeedDemoRoute: typeof ApiAdminSeedDemoRoute
  ApiAdminStaffInvitesRoute: typeof ApiAdminStaffInvitesRoute
  ApiAttendanceFeedRoute: typeof ApiAttendanceFeedRoute
  ApiAttendanceHistoryRoute: typeof ApiAttendanceHistoryRoute
  ApiAuthDemoLoginRoute: typeof ApiAuthDemoLoginRoute
  ApiAuthLoginDirectRoute: typeof ApiAuthLoginDirectRoute
  ApiAuthRegisterOrgRoute: typeof ApiAuthRegisterOrgRoute
  ApiCheckInScanRoute: typeof ApiCheckInScanRoute
  ApiKioskPairRoute: typeof ApiKioskPairRoute
  ApiKioskPairCodeRoute: typeof ApiKioskPairCodeRoute
  ApiKioskTokenRoute: typeof ApiKioskTokenRoute
  ApiLocationsRevokeRoute: typeof ApiLocationsRevokeRoute
  ApiPushNotificationsRoute: typeof ApiPushNotificationsRoute
  ApiPushPreferencesRoute: typeof ApiPushPreferencesRoute
  ApiPushSendRoute: typeof ApiPushSendRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushVapidKeyRoute: typeof ApiPushVapidKeyRoute
  ApiAnnouncementsIndexRoute: typeof ApiAnnouncementsIndexRoute
  ApiLocationsIndexRoute: typeof ApiLocationsIndexRoute
  ApiOrganizationIndexRoute: typeof ApiOrganizationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/roles': {
      id: '/api/admin/roles'
      path: '/api/admin/roles'
      fullPath: '/api/admin/roles'
      preLoaderRoute: typeof ApiAdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/seed-demo': {
      id: '/api/admin/seed-demo'
      path: '/api/admin/seed-demo'
      fullPath: '/api/admin/seed-demo'
      preLoaderRoute: typeof ApiAdminSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/staff-invites': {
      id: '/api/admin/staff-invites'
      path: '/api/admin/staff-invites'
      fullPath: '/api/admin/staff-invites'
      preLoaderRoute: typeof ApiAdminStaffInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcements/': {
      id: '/api/announcements/'
      path: '/api/announcements'
      fullPath: '/api/announcements/'
      preLoaderRoute: typeof ApiAnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/feed': {
      id: '/api/attendance/feed'
      path: '/api/attendance/feed'
      fullPath: '/api/attendance/feed'
      preLoaderRoute: typeof ApiAttendanceFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/history': {
      id: '/api/attendance/history'
      path: '/api/attendance/history'
      fullPath: '/api/attendance/history'
      preLoaderRoute: typeof ApiAttendanceHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/demo-login': {
      id: '/api/auth/demo-login'
      path: '/api/auth/demo-login'
      fullPath: '/api/auth/demo-login'
      preLoaderRoute: typeof ApiAuthDemoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login-direct': {
      id: '/api/auth/login-direct'
      path: '/api/auth/login-direct'
      fullPath: '/api/auth/login-direct'
      preLoaderRoute: typeof ApiAuthLoginDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register-org': {
      id: '/api/auth/register-org'
      path: '/api/auth/register-org'
      fullPath: '/api/auth/register-org'
      preLoaderRoute: typeof ApiAuthRegisterOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-in/scan': {
      id: '/api/check-in/scan'
      path: '/api/check-in/scan'
      fullPath: '/api/check-in/scan'
      preLoaderRoute: typeof ApiCheckInScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kiosk/pair': {
      id: '/api/kiosk/pair'
      path: '/api/kiosk/pair'
      fullPath: '/api/kiosk/pair'
      preLoaderRoute: typeof ApiKioskPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kiosk/pair-code': {
      id: '/api/kiosk/pair-code'
      path: '/api/kiosk/pair-code'
      fullPath: '/api/kiosk/pair-code'
      preLoaderRoute: typeof ApiKioskPairCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kiosk/token': {
      id: '/api/kiosk/token'
      path: '/api/kiosk/token'
      fullPath: '/api/kiosk/token'
      preLoaderRoute: typeof ApiKioskTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/locations/': {
      id: '/api/locations/'
      path: '/api/locations'
      fullPath: '/api/locations/'
      preLoaderRoute: typeof ApiLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/locations/revoke': {
      id: '/api/locations/revoke'
      path: '/api/locations/revoke'
      fullPath: '/api/locations/revoke'
      preLoaderRoute: typeof ApiLocationsRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/': {
      id: '/api/organization/'
      path: '/api/organization'
      fullPath: '/api/organization/'
      preLoaderRoute: typeof ApiOrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/notifications': {
      id: '/api/push/notifications'
      path: '/api/push/notifications'
      fullPath: '/api/push/notifications'
      preLoaderRoute: typeof ApiPushNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/preferences': {
      id: '/api/push/preferences'
      path: '/api/push/preferences'
      fullPath: '/api/push/preferences'
      preLoaderRoute: typeof ApiPushPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/send': {
      id: '/api/push/send'
      path: '/api/push/send'
      fullPath: '/api/push/send'
      preLoaderRoute: typeof ApiPushSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/vapid-key': {
      id: '/api/push/vapid-key'
      path: '/api/push/vapid-key'
      fullPath: '/api/push/vapid-key'
      preLoaderRoute: typeof ApiPushVapidKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KioskRoute: KioskRoute,
  PrivacyRoute: PrivacyRoute,
  ScanRoute: ScanRoute,
  TermsRoute: TermsRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  ApiAdminRolesRoute: ApiAdminRolesRoute,
  ApiAdminSeedDemoRoute: ApiAdminSeedDemoRoute,
  ApiAdminStaffInvitesRoute: ApiAdminStaffInvitesRoute,
  ApiAttendanceFeedRoute: ApiAttendanceFeedRoute,
  ApiAttendanceHistoryRoute: ApiAttendanceHistoryRoute,
  ApiAuthDemoLoginRoute: ApiAuthDemoLoginRoute,
  ApiAuthLoginDirectRoute: ApiAuthLoginDirectRoute,
  ApiAuthRegisterOrgRoute: ApiAuthRegisterOrgRoute,
  ApiCheckInScanRoute: ApiCheckInScanRoute,
  ApiKioskPairRoute: ApiKioskPairRoute,
  ApiKioskPairCodeRoute: ApiKioskPairCodeRoute,
  ApiKioskTokenRoute: ApiKioskTokenRoute,
  ApiLocationsRevokeRoute: ApiLocationsRevokeRoute,
  ApiPushNotificationsRoute: ApiPushNotificationsRoute,
  ApiPushPreferencesRoute: ApiPushPreferencesRoute,
  ApiPushSendRoute: ApiPushSendRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushVapidKeyRoute: ApiPushVapidKeyRoute,
  ApiAnnouncementsIndexRoute: ApiAnnouncementsIndexRoute,
  ApiLocationsIndexRoute: ApiLocationsIndexRoute,
  ApiOrganizationIndexRoute: ApiOrganizationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
